# Generated by Django 6.0.3 on 2026-04-04 04:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("intake", "0002_seed_barangays"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("A", "Group A - Applicant Requirements"),
                            ("B", "Group B - Office-Generated"),
                            ("C", "Group C - Post-Award"),
                        ],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "is_required_for_form",
                    models.BooleanField(
                        default=True,
                        help_text="If True, this must be complete before application form is generated",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Requirement",
                "verbose_name_plural": "Requirements",
                "ordering": ["group", "order"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "application_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft - Form Generated"),
                            ("completed", "Completed - Signed by Applicant"),
                            ("routing", "Under Signatory Routing"),
                            ("oic_signed", "Signed by OIC"),
                            ("head_signed", "Signed by Head - Fully Approved"),
                            ("standby", "Fully Approved - On Standby"),
                            ("awarded", "Lot Awarded"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("form_generated_at", models.DateTimeField(auto_now_add=True)),
                ("applicant_signed_at", models.DateTimeField(blank=True, null=True)),
                ("notarial_completed", models.BooleanField(default=False)),
                ("notarial_completed_at", models.DateTimeField(blank=True, null=True)),
                ("engineering_completed", models.BooleanField(default=False)),
                (
                    "engineering_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("fully_approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "standby_position",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("standby_entered_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application",
                        to="intake.applicant",
                    ),
                ),
                (
                    "form_generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SignatoryRouting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("received", "Received by Third Member"),
                            ("forwarded_oic", "Forwarded to OIC"),
                            ("signed_oic", "Signed by OIC"),
                            ("forwarded_head", "Forwarded to Head"),
                            ("signed_head", "Signed by Head - Complete"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "action_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routing_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routing_steps",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signatory Routing Step",
                "verbose_name_plural": "Signatory Routing Steps",
                "ordering": ["application", "action_at"],
            },
        ),
        migrations.CreateModel(
            name="FacilitatedService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("notarial", "Notarial Services"),
                            ("engineering", "Engineering Assessment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilitated_services",
                        to="applications.application",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Facilitated Service",
                "verbose_name_plural": "Facilitated Services",
                "ordering": ["application", "service_type"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("application", "service_type"),
                        name="unique_application_service",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RequirementSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected - Resubmit Required"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirement_submissions",
                        to="intake.applicant",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="applications.requirement",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_requirements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Requirement Submission",
                "verbose_name_plural": "Requirement Submissions",
                "ordering": ["applicant", "requirement__order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("applicant", "requirement"),
                        name="unique_applicant_requirement",
                    )
                ],
            },
        ),
    ]
