# Generated by Django 5.2.7 on 2026-04-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_electricityconnection_lotawarding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signatoryrouting",
            name="step",
            field=models.CharField(
                choices=[
                    ("received", "Received - Processing"),
                    ("forwarded_oic", "Forwarded to OIC"),
                    ("signed_oic", "Signed by OIC"),
                    ("forwarded_head", "Forwarded to Head"),
                    ("signed_head", "Signed by Head - Complete"),
                ],
                max_length=20,
            ),
        ),
    ]
