# Generated by Django 6.0.3 on 2026-04-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_move_queueentry_from_intake"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistProxy",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("reason", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("blacklisted_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Blacklist (Module 2 view)",
                "verbose_name_plural": "Blacklist (Module 2 view)",
                "db_table": "intake_blacklist",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CDRRMOCertificationProxy",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("status", models.CharField(max_length=20)),
                ("disposition_source", models.CharField(max_length=20)),
                ("declared_location", models.TextField()),
                ("requested_at", models.DateTimeField()),
                ("certified_at", models.DateTimeField(blank=True, null=True)),
                ("certification_notes", models.TextField(blank=True)),
                ("office_intake_notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "CDRRMO Certification (Module 2 view)",
                "verbose_name_plural": "CDRRMO Certifications (Module 2 view)",
                "db_table": "intake_cdrrmocertification",
                "managed": False,
            },
        ),
    ]
