# Generated by Django 5.2.10 on 2026-04-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0007_remove_blacklistproxy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facilitatedservice",
            name="application",
        ),
        migrations.RemoveField(
            model_name="facilitatedservice",
            name="completed_by",
        ),
        migrations.RemoveField(
            model_name="facilitatedservice",
            name="initiated_by",
        ),
        migrations.RemoveField(
            model_name="lotawarding",
            name="application",
        ),
        migrations.RemoveField(
            model_name="lotawarding",
            name="awarded_by",
        ),
        migrations.AlterField(
            model_name="queueentry",
            name="queue_type",
            field=models.CharField(
                choices=[
                    ("priority", "Priority Queue - Danger Zone"),
                    ("walk_in", "Walk-in Queue - FIFO"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="ElectricityConnection",
        ),
        migrations.DeleteModel(
            name="FacilitatedService",
        ),
        migrations.DeleteModel(
            name="LotAwarding",
        ),
    ]
