# Generated by Django 5.2.10 on 2026-04-24 06:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_remove_facilitatedservice_application_and_more"),
        ("intake", "0032_move_cdrrmo_and_field_photos_from_intake"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTable(
            name="cdrrmocertificationproxy",
            table="applications_cdrrmocertification",
        ),
        migrations.CreateModel(
            name="CDRRMOCertification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "declared_location",
                    models.TextField(
                        help_text="Riverbank, riverside, flood-prone area, etc.",
                        verbose_name="Declared Danger Zone Location",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending CDRRMO verification (claim on file)"),
                            ("certified", "Certified - Danger Zone"),
                            ("not_certified", "Not Certified"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "disposition_source",
                    models.CharField(
                        choices=[
                            ("pending", "No disposition recorded"),
                            (
                                "office_intake",
                                "Official CDRRMO paperwork filed at THA intake",
                            ),
                            ("field_unit", "Field unit / Ronda on-site verification"),
                        ],
                        default="pending",
                        help_text="Intake-filed CDRRMO documents vs. field/Ronda on-site verification (different workflows).",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("certified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "certification_notes",
                    models.TextField(
                        blank=True,
                        help_text="Remarks from field / Ronda on-site verification (not intake receiving log).",
                    ),
                ),
                (
                    "office_intake_notes",
                    models.TextField(
                        blank=True,
                        help_text="Receiving log when official CDRRMO certification is filed at THA intake.",
                    ),
                ),
                (
                    "applicant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cdrrmo_certification",
                        to="intake.applicant",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cdrrmo_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "result_recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cdrrmo_results_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CDRRMO Certification",
                "verbose_name_plural": "CDRRMO Certifications",
            },
        ),
        migrations.CreateModel(
            name="FieldVerificationPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="field_verification/%Y/%m/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "certification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_photos",
                        to="applications.cdrrmocertification",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_verification_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Field verification photo",
                "verbose_name_plural": "Field verification photos",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
