# Generated by Django 5.2.10 on 2026-05-04 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0013_retire_signatory_routing_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="engineering_completed",
        ),
        migrations.RemoveField(
            model_name="application",
            name="engineering_completed_at",
        ),
        migrations.RemoveField(
            model_name="application",
            name="notarial_completed",
        ),
        migrations.RemoveField(
            model_name="application",
            name="notarial_completed_at",
        ),
    ]
