# Generated by Django 5.2.10 on 2026-05-06 13:04

from django.db import migrations, models


def migrate_legacy_full_approval_to_standby(apps, schema_editor):
    Application = apps.get_model("applications", "Application")
    Application.objects.filter(status="legacy_full_approval").update(status="standby")


def reverse_standby_to_legacy_full_approval(apps, schema_editor):
    # No safe reverse mapping once statuses are consolidated into standby.
    return


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0014_remove_facilitated_service_flags"),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_full_approval_to_standby, reverse_standby_to_legacy_full_approval),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft - Form Generated"),
                    ("completed", "Completed - Signed by Applicant"),
                    ("standby", "Fully Approved - On Standby"),
                    ("awarded", "Lot Awarded"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
