# Generated by Django 6.0.3 on 2026-04-03 05:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Barangay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Barangay",
                "verbose_name_plural": "Barangays",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Full Name"),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Contact Number"
                    ),
                ),
                (
                    "current_address",
                    models.TextField(verbose_name="Current Address/Location"),
                ),
                (
                    "years_residing",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Years at Current Location"
                    ),
                ),
                (
                    "monthly_income",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Monthly Household Income (₱)",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("landowner", "Channel A - Landowner Submission"),
                            ("danger_zone", "Channel B - Danger Zone Walk-in"),
                            ("walk_in", "Channel C - Regular Walk-in"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Eligibility Check"),
                            ("pending_cdrrmo", "Pending CDRRMO Certification"),
                            ("eligible", "Eligible - In Queue"),
                            ("disqualified", "Disqualified"),
                            ("requirements", "Submitting Requirements"),
                            ("application", "Application In Progress"),
                            ("standby", "Fully Approved - Standby"),
                            ("awarded", "Lot Awarded"),
                            ("blacklisted", "Blacklisted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "has_property_in_talisay",
                    models.BooleanField(
                        default=False, verbose_name="Owns Property in Talisay City"
                    ),
                ),
                ("disqualification_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("eligibility_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "eligibility_checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eligibility_checked_applicants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_applicants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "barangay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applicants",
                        to="intake.barangay",
                        verbose_name="Barangay of Origin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Applicant",
                "verbose_name_plural": "Applicants",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Blacklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("repossession", "Housing Unit Repossessed"),
                            ("fraud", "Fraudulent Information"),
                            ("violation", "Violation of Housing Rules"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("blacklisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blacklist_entries",
                        to="intake.applicant",
                    ),
                ),
                (
                    "blacklisted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blacklist_entries_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blacklist Entry",
                "verbose_name_plural": "Blacklist",
                "ordering": ["-blacklisted_at"],
            },
        ),
        migrations.CreateModel(
            name="CDRRMOCertification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "declared_location",
                    models.TextField(
                        help_text="Riverbank, riverside, flood-prone area, etc.",
                        verbose_name="Declared Danger Zone Location",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending CDRRMO Visit"),
                            ("certified", "Certified - Danger Zone"),
                            ("not_certified", "Not Certified"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("certified_at", models.DateTimeField(blank=True, null=True)),
                ("certification_notes", models.TextField(blank=True)),
                (
                    "applicant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cdrrmo_certification",
                        to="intake.applicant",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cdrrmo_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "result_recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cdrrmo_results_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CDRRMO Certification",
                "verbose_name_plural": "CDRRMO Certifications",
            },
        ),
        migrations.CreateModel(
            name="HouseholdMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Spouse"),
                            ("child", "Child"),
                            ("parent", "Parent"),
                            ("sibling", "Sibling"),
                            ("grandchild", "Grandchild"),
                            ("other", "Other Relative"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="household_members",
                        to="intake.applicant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Household Member",
                "verbose_name_plural": "Household Members",
                "ordering": ["applicant", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ISFRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Full Name"),
                ),
                (
                    "household_members",
                    models.PositiveIntegerField(
                        verbose_name="Number of Household Members"
                    ),
                ),
                (
                    "monthly_income",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Monthly Income (₱)",
                    ),
                ),
                (
                    "years_residing",
                    models.PositiveIntegerField(
                        verbose_name="Years Residing on Property"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Contact Number"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("eligible", "Eligible - Converted to Applicant"),
                            ("disqualified", "Disqualified"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("disqualification_reason", models.TextField(blank=True)),
                ("eligibility_checked_at", models.DateTimeField(blank=True, null=True)),
                ("converted_to_applicant", models.BooleanField(default=False)),
                ("applicant_created_at", models.DateTimeField(blank=True, null=True)),
                ("registration_sms_sent", models.BooleanField(default=False)),
                ("eligibility_sms_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "eligibility_checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_isf_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ISF Record",
                "verbose_name_plural": "ISF Records",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="applicant",
            name="isf_record",
            field=models.OneToOneField(
                blank=True,
                help_text="Links to original ISF record if from landowner submission",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applicant_profile",
                to="intake.isfrecord",
            ),
        ),
        migrations.CreateModel(
            name="LandownerSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "landowner_name",
                    models.CharField(
                        max_length=255, verbose_name="Landowner Full Name"
                    ),
                ),
                (
                    "landowner_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Contact Number"
                    ),
                ),
                (
                    "landowner_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email Address"
                    ),
                ),
                ("property_address", models.TextField(verbose_name="Property Address")),
                ("barangay", models.CharField(max_length=100, verbose_name="Barangay")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewed", "Reviewed"),
                            ("processed", "Processed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, verbose_name="Staff Notes")),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Landowner Submission",
                "verbose_name_plural": "Landowner Submissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddField(
            model_name="isfrecord",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="isf_records",
                to="intake.landownersubmission",
            ),
        ),
        migrations.CreateModel(
            name="SMSLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipient_phone", models.CharField(max_length=20)),
                ("message_content", models.TextField()),
                (
                    "trigger_event",
                    models.CharField(
                        help_text="Event that triggered this SMS (registration, eligibility_passed, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_logs",
                        to="intake.applicant",
                    ),
                ),
                (
                    "isf_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_logs",
                        to="intake.isfrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Log",
                "verbose_name_plural": "SMS Logs",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="QueueEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "queue_type",
                    models.CharField(
                        choices=[
                            ("priority", "Priority Queue"),
                            ("walk_in", "Walk-in FIFO Queue"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        help_text="Position number in the queue (FIFO order)",
                        verbose_name="Queue Position",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active - Waiting"),
                            ("notified", "Notified for Requirements"),
                            ("processing", "Processing Application"),
                            ("completed", "Completed - Moved to Application"),
                            ("removed", "Removed from Queue"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("entered_at", models.DateTimeField(auto_now_add=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="queue_entries_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_entries",
                        to="intake.applicant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Queue Entry",
                "verbose_name_plural": "Queue Entries",
                "ordering": ["queue_type", "position"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("queue_type", "position"),
                        name="unique_active_queue_position",
                    )
                ],
            },
        ),
    ]
