# Generated by Django 6.0.3 on 2026-04-04 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0002_seed_barangays"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="landownersubmission",
            name="submitted_by_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_submissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Submitted by Staff",
            ),
        ),
        migrations.AlterField(
            model_name="landownersubmission",
            name="barangay",
            field=models.CharField(blank=True, max_length=100, verbose_name="Barangay"),
        ),
    ]
