# Generated by Django 6.0.3 on 2026-04-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0003_add_submitted_by_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="danger_zone_location",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Specific Danger Zone Location"
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="danger_zone_type",
            field=models.CharField(
                blank=True,
                help_text="flood_prone, landslide, storm_surge, river_bank, cliff_edge, coastal, other",
                max_length=50,
                verbose_name="Type of Danger Zone",
            ),
        ),
    ]
