# Generated by Django 6.0.3 on 2026-04-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0004_applicant_danger_zone_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="isfrecord",
            name="barangay",
            field=models.CharField(blank=True, max_length=100, verbose_name="Barangay"),
        ),
    ]
