# Generated by Django 6.0.3 on 2026-04-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0005_add_isf_barangay"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="household_size",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of household members as declared during registration",
                verbose_name="Declared Household Size",
            ),
        ),
    ]
