# Generated by Django 6.0.3 on 2026-04-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0006_add_household_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="doc_2x2_picture",
            field=models.BooleanField(default=False, verbose_name="2x2 Picture"),
        ),
        migrations.AddField(
            model_name="applicant",
            name="doc_brgy_indigency",
            field=models.BooleanField(
                default=False, verbose_name="Brgy. Certificate of Indigency"
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="doc_brgy_residency",
            field=models.BooleanField(
                default=False, verbose_name="Brgy. Certificate of Residency"
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="doc_cedula",
            field=models.BooleanField(default=False, verbose_name="Cedula"),
        ),
        migrations.AddField(
            model_name="applicant",
            name="doc_no_property",
            field=models.BooleanField(
                default=False, verbose_name="Certificate of No Property"
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="doc_police_clearance",
            field=models.BooleanField(default=False, verbose_name="Police Clearance"),
        ),
        migrations.AddField(
            model_name="applicant",
            name="doc_sketch_location",
            field=models.BooleanField(
                default=False, verbose_name="Sketch of House Location"
            ),
        ),
        migrations.AddField(
            model_name="isfrecord",
            name="doc_2x2_picture",
            field=models.BooleanField(default=False, verbose_name="2x2 Picture"),
        ),
        migrations.AddField(
            model_name="isfrecord",
            name="doc_brgy_indigency",
            field=models.BooleanField(
                default=False, verbose_name="Brgy. Certificate of Indigency"
            ),
        ),
        migrations.AddField(
            model_name="isfrecord",
            name="doc_brgy_residency",
            field=models.BooleanField(
                default=False, verbose_name="Brgy. Certificate of Residency"
            ),
        ),
        migrations.AddField(
            model_name="isfrecord",
            name="doc_cedula",
            field=models.BooleanField(default=False, verbose_name="Cedula"),
        ),
        migrations.AddField(
            model_name="isfrecord",
            name="doc_no_property",
            field=models.BooleanField(
                default=False, verbose_name="Certificate of No Property"
            ),
        ),
        migrations.AddField(
            model_name="isfrecord",
            name="doc_police_clearance",
            field=models.BooleanField(default=False, verbose_name="Police Clearance"),
        ),
        migrations.AddField(
            model_name="isfrecord",
            name="doc_sketch_location",
            field=models.BooleanField(
                default=False, verbose_name="Sketch of House Location"
            ),
        ),
    ]
