# Generated by Django 6.0.3 on 2026-04-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0007_add_document_checklist"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="eligibility_sms_sent",
            field=models.BooleanField(
                default=False, verbose_name="Eligibility SMS Sent"
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="registration_sms_sent",
            field=models.BooleanField(
                default=False, verbose_name="Registration SMS Sent"
            ),
        ),
    ]
