# Generated by Django 5.2.7 on 2026-04-10 04:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0008_add_applicant_sms_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="isfrecord",
            name="has_been_edited",
            field=models.BooleanField(
                default=False,
                help_text="Track if staff corrected any data after initial submission",
                verbose_name="Has Been Edited by Staff",
            ),
        ),
        migrations.CreateModel(
            name="ISFEditAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Field edited: monthly_income, household_members, years_residing, phone_number, barangay",
                        max_length=50,
                    ),
                ),
                ("original_value", models.TextField()),
                ("new_value", models.TextField()),
                (
                    "edit_reason",
                    models.TextField(
                        help_text="Why this data correction was necessary",
                        verbose_name="Reason for Edit",
                    ),
                ),
                ("edited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="isf_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "isf_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_audits",
                        to="intake.isfrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "ISF Edit Audit",
                "verbose_name_plural": "ISF Edit Audits",
                "ordering": ["-edited_at"],
            },
        ),
    ]
