# Generated by Django 5.2.7 on 2026-04-10 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0009_isfrecord_has_been_edited_isfeditaudit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="isfrecord",
            name="submitted_by_staff",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who entered this ISF data (walk-in). Null if from public portal.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_isf_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Submitted by Staff",
            ),
        ),
    ]
