# Generated by Django 5.2.7 on 2026-04-15 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0010_isfrecord_submitted_by_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="isfrecord",
            name="submission",
        ),
        migrations.DeleteModel(
            name="LandownerSubmission",
        ),
    ]
