# Generated by Django 5.2.7 on 2026-04-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0011_remove_isfrecord_submission_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="isfrecord",
            name="eligibility_checked_by",
        ),
        migrations.RemoveField(
            model_name="isfrecord",
            name="submitted_by_staff",
        ),
        migrations.RemoveField(
            model_name="smslog",
            name="isf_record",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="isf_record",
        ),
        migrations.AlterField(
            model_name="applicant",
            name="channel",
            field=models.CharField(
                choices=[
                    ("danger_zone", "Channel B - Danger Zone Walk-in"),
                    ("walk_in", "Channel C - Regular Walk-in"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="ISFEditAudit",
        ),
        migrations.DeleteModel(
            name="ISFRecord",
        ),
    ]
