# Generated by Django 5.2.7 on 2026-04-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0012_remove_isfrecord_eligibility_checked_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="channel",
            field=models.CharField(
                choices=[("danger_zone", "Channel B - Danger Zone Walk-in")],
                max_length=20,
            ),
        ),
    ]
