# Generated by Django 5.2.7 on 2026-04-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0013_remove_channel_c_walkin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queueentry",
            name="queue_type",
            field=models.CharField(
                choices=[("priority", "Priority Queue - Danger Zone")], max_length=20
            ),
        ),
    ]
