# Generated by Django 5.2.7 on 2026-04-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0014_remove_walkin_queue_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Age"
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="place_of_birth",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Place of Birth"
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                verbose_name="Sex",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="spouse_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Name of Spouse"
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="spouse_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Spouse Contact Number"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Applicant Contact Number"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="years_residing",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Years Residing in Talisay"
            ),
        ),
    ]
