# Generated by Django 5.2.7 on 2026-04-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0015_add_applicant_personal_and_spouse_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="smslog",
            name="external_id",
            field=models.CharField(
                blank=True, help_text="Twilio message SID", max_length=100
            ),
        ),
    ]
