# Generated by Django 5.2.7 on 2026-04-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0016_add_external_id_to_smslog"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="employment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("employed", "Employed"),
                    ("self_employed", "Self-Employed"),
                    ("unemployed", "Unemployed"),
                    ("retired", "Retired"),
                    ("other", "Other"),
                ],
                max_length=50,
                verbose_name="Status of Employment",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="occupation",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Occupation"
            ),
        ),
    ]
