# Generated by Django 5.2.7 on 2026-04-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0017_applicant_employment_status_applicant_occupation"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="document_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline by which all 7 documents must be submitted",
                null=True,
                verbose_name="Document Submission Deadline",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="documents_submitted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When all 7 documents were completed",
                null=True,
                verbose_name="Documents Completed Date",
            ),
        ),
    ]
