# Generated by Django 5.2.7 on 2026-04-20 04:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0019_fieldverificationphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="first_name",
            field=models.CharField(
                default="", max_length=100, verbose_name="First Name (Given Name)"
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="last_name",
            field=models.CharField(
                default="", max_length=100, verbose_name="Last Name (Surname)"
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="middle_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Middle Name"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="full_name",
            field=models.CharField(
                editable=False, max_length=255, verbose_name="Full Name"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Format: 09XXXXXXXXXX (11 digits)",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_phone",
                        message="Phone number must be in format 09XXXXXXXXXX (11 digits)",
                        regex="^09\\d{9}$",
                    )
                ],
                verbose_name="Applicant Contact Number",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="spouse_phone",
            field=models.CharField(
                blank=True,
                help_text="Format: 09XXXXXXXXXX (11 digits)",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_phone",
                        message="Phone number must be in format 09XXXXXXXXXX (11 digits)",
                        regex="^09\\d{9}$",
                    )
                ],
                verbose_name="Spouse Contact Number",
            ),
        ),
    ]
