# Generated by Django 5.2.7 on 2026-04-20 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0020_add_name_fields_and_phone_validation"),
    ]

    operations = [
        migrations.AddField(
            model_name="householdmember",
            name="age",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(120)],
                verbose_name="Age",
            ),
        ),
        migrations.AddField(
            model_name="householdmember",
            name="civil_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("widowed", "Widowed"),
                    ("divorced", "Divorced"),
                    ("separated", "Separated"),
                    ("common_law", "Common-law"),
                ],
                default="single",
                max_length=20,
                verbose_name="Civil Status",
            ),
        ),
        migrations.AlterField(
            model_name="householdmember",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
        migrations.AlterField(
            model_name="householdmember",
            name="full_name",
            field=models.CharField(max_length=100, verbose_name="Full Name"),
        ),
        migrations.AlterField(
            model_name="householdmember",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("spouse", "Spouse"),
                    ("child", "Child"),
                    ("parent", "Parent"),
                    ("sibling", "Sibling"),
                    ("grandchild", "Grandchild"),
                    ("other", "Other Relative"),
                ],
                max_length=20,
                verbose_name="Relationship to Applicant",
            ),
        ),
        migrations.AlterField(
            model_name="householdmember",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                verbose_name="Sex",
            ),
        ),
    ]
