# Generated by Django — separates THA intake filing from field unit verification

from django.db import migrations, models


def backfill_cdrrmo_disposition(apps, schema_editor):
    CDRRMOCertification = apps.get_model('intake', 'CDRRMOCertification')
    FieldVerificationPhoto = apps.get_model('intake', 'FieldVerificationPhoto')

    for cert in CDRRMOCertification.objects.exclude(status='pending'):
        has_photos = FieldVerificationPhoto.objects.filter(certification_id=cert.pk).exists()
        notes = cert.certification_notes or ''
        if 'Official CDRRMO certification received at THA intake' in notes:
            cert.disposition_source = 'office_intake'
            cert.office_intake_notes = notes
            cert.certification_notes = ''
            cert.save(update_fields=['disposition_source', 'office_intake_notes', 'certification_notes'])
        else:
            cert.disposition_source = 'field_unit'
            cert.save(update_fields=['disposition_source'])


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0021_add_household_member_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdrrmocertification',
            name='disposition_source',
            field=models.CharField(
                choices=[
                    ('pending', 'No disposition recorded'),
                    ('office_intake', 'Official CDRRMO paperwork filed at THA intake'),
                    ('field_unit', 'Field unit / Ronda on-site verification'),
                ],
                default='pending',
                help_text='Whether the current disposition came from intake-filed CDRRMO documents or from field inspection.',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='cdrrmocertification',
            name='office_intake_notes',
            field=models.TextField(
                blank=True,
                help_text='Receiving log when official CDRRMO certification is filed at THA (not field inspection remarks).',
            ),
        ),
        migrations.RunPython(backfill_cdrrmo_disposition, migrations.RunPython.noop),
    ]
