# Generated by Django 6.0.3 on 2026-04-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0022_cdrrmocertification_disposition_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cdrrmocertification",
            name="certification_notes",
            field=models.TextField(
                blank=True,
                help_text="Remarks from field / Ronda on-site verification (not intake receiving log).",
            ),
        ),
        migrations.AlterField(
            model_name="cdrrmocertification",
            name="disposition_source",
            field=models.CharField(
                choices=[
                    ("pending", "No disposition recorded"),
                    ("office_intake", "Official CDRRMO paperwork filed at THA intake"),
                    ("field_unit", "Field unit / Ronda on-site verification"),
                ],
                default="pending",
                help_text="Intake-filed CDRRMO documents vs. field/Ronda on-site verification (different workflows).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cdrrmocertification",
            name="office_intake_notes",
            field=models.TextField(
                blank=True,
                help_text="Receiving log when official CDRRMO certification is filed at THA intake.",
            ),
        ),
    ]
