# Generated by Django 5.2.10 on 2026-04-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0026_hazarddeclarationaudit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending eligibility check"),
                    ("pending_cdrrmo", "Pending CDRRMO verification (hazard claim)"),
                    ("eligible", "Eligible - In Queue"),
                    ("disqualified", "Disqualified"),
                    ("requirements", "Submitting Requirements"),
                    ("application", "Application In Progress"),
                    ("standby", "Fully Approved - Standby"),
                    ("awarded", "Lot Awarded"),
                    ("blacklisted", "Blacklisted"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cdrrmocertification",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending CDRRMO verification (claim on file)"),
                    ("certified", "Certified - Danger Zone"),
                    ("not_certified", "Not Certified"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
