# Generated by Django 5.2.10 on 2026-04-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0026_remove_queueentry"),
        ("intake", "0027_alter_applicant_status_and_more"),
    ]

    operations = []
