# Generated by Django 5.2.10 on 2026-04-24 06:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0030_applicant_evaluation_approval_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reference_number_snapshot",
                    models.CharField(db_index=True, max_length=50),
                ),
                ("full_name_snapshot", models.CharField(max_length=255)),
                ("date_of_birth_snapshot", models.DateField(blank=True, null=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("channel_a", "Channel A — Walk-in"),
                            ("channel_b_no_hazard", "Channel B — No hazard"),
                            ("channel_b_hazard", "Channel B — Hazard"),
                            ("channel_c", "Channel C — Landowner"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "queue_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("priority", "Priority Queue"),
                            ("walk_in", "Walk-in Queue"),
                        ],
                        help_text="Queue type assigned upon Module 2 entry",
                        max_length=20,
                    ),
                ),
                (
                    "barangay_name_snapshot",
                    models.CharField(blank=True, max_length=100),
                ),
                ("sms_sent", models.BooleanField(default=False)),
                ("sms_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cdrrmo_certified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether CDRRMO certificate was present at archive time",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archives",
                        to="intake.applicant",
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_applicants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Intake Archive",
                "verbose_name_plural": "Intake Archives",
                "ordering": ["-archived_at"],
                "indexes": [
                    models.Index(
                        fields=["archived_at"], name="intake_arch_archive_03e8a0_idx"
                    ),
                    models.Index(
                        fields=["reference_number_snapshot"],
                        name="intake_arch_referen_9ee1e9_idx",
                    ),
                    models.Index(
                        fields=["channel"], name="intake_arch_channel_9dc051_idx"
                    ),
                ],
            },
        ),
    ]
