# Generated by Django 5.2.10 on 2026-04-24 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0031_add_archive_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fieldverificationphoto",
            name="certification",
        ),
        migrations.RemoveField(
            model_name="fieldverificationphoto",
            name="uploaded_by",
        ),
        migrations.RemoveField(
            model_name="hazarddeclarationaudit",
            name="applicant",
        ),
        migrations.RemoveField(
            model_name="hazarddeclarationaudit",
            name="changed_by",
        ),
        migrations.DeleteModel(
            name="CDRRMOCertification",
        ),
        migrations.DeleteModel(
            name="FieldVerificationPhoto",
        ),
        migrations.DeleteModel(
            name="HazardDeclarationAudit",
        ),
    ]
