# Generated by Django 5.2.10 on 2026-04-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0032_move_cdrrmo_and_field_photos_from_intake"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="extension_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Jr., Sr., II, III, IV, etc.",
                max_length=50,
                verbose_name="Extension Name",
            ),
        ),
    ]
