# Generated by Django 5.2.10 on 2026-04-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0033_add_extension_name_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="extension_name_snapshot",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="archive",
            name="first_name_snapshot",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="archive",
            name="last_name_snapshot",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="archive",
            name="middle_name_snapshot",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
