# Generated by Django 5.2.10 on 2026-04-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0035_applicant_is_registered_voter_talisay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="householdmember",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("spouse", "Spouse"),
                    ("child", "Child"),
                    ("parent", "Parent"),
                    ("sibling", "Sibling"),
                    ("grandchild", "Grandchild"),
                    ("live_in_partner", "Live-in Partner"),
                    ("other", "Other Relative"),
                ],
                max_length=20,
                verbose_name="Relationship to Applicant",
            ),
        ),
    ]
