# Generated by Django 5.2.10 on 2026-04-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0037_applicant_displacement_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="archive",
            options={
                "ordering": ["archived_at"],
                "verbose_name": "Intake Archive",
                "verbose_name_plural": "Intake Archives",
            },
        ),
        migrations.AlterField(
            model_name="applicant",
            name="displacement_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not declared"),
                    ("danger_zone", "Danger Zone / Hazard Area"),
                    ("ejected", "Ejected from Previous Residence"),
                    ("relocated", "Relocated Due to Expansion or Project Development"),
                    ("not_abc", "None of A, B, or C (Other / Not listed)"),
                ],
                default="",
                help_text="Module 2 Layer 3 displacement classification.",
                max_length=20,
                verbose_name="Displacement Reason",
            ),
        ),
    ]
