# Generated by Django 5.2.10 on 2026-05-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0038_applicant_displacement_not_abc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending eligibility check"),
                    ("pending_cdrrmo", "Pending CDRRMO verification (hazard claim)"),
                    (
                        "pending_followup",
                        "Pending Follow-up (failed eligibility check)",
                    ),
                    ("eligible", "Eligible - In Queue"),
                    ("disqualified", "Disqualified"),
                    ("requirements", "Submitting Requirements"),
                    ("application", "Application In Progress"),
                    ("standby", "Fully Approved - Standby"),
                    ("awarded", "Lot Awarded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
