# Generated by Django 5.2.10 on 2026-05-04 15:35

from django.db import migrations, models


def _rebuild_full_name(first, middle, last, ext):
    parts = [first or "", middle or "", last or ""]
    base = " ".join(p for p in parts if p).strip()
    if ext:
        return f"{base}, {ext}".strip()
    return base


def truncate_applicant_and_archive_names(apps, schema_editor):
    Applicant = apps.get_model("intake", "Applicant")
    Archive = apps.get_model("intake", "Archive")

    for row in Applicant.objects.all().iterator():
        ln = (row.last_name or "")[:10]
        fn = (row.first_name or "")[:15]
        mn = (row.middle_name or "")[:10]
        en = (row.extension_name or "")[:5]
        full = _rebuild_full_name(fn, mn, ln, en)[:255]
        if (
            row.last_name != ln
            or row.first_name != fn
            or row.middle_name != mn
            or row.extension_name != en
            or row.full_name != full
        ):
            Applicant.objects.filter(pk=row.pk).update(
                last_name=ln,
                first_name=fn,
                middle_name=mn,
                extension_name=en,
                full_name=full,
            )

    for row in Archive.objects.all().iterator():
        ln = (row.last_name_snapshot or "")[:10]
        fn = (row.first_name_snapshot or "")[:15]
        mn = (row.middle_name_snapshot or "")[:10]
        en = (row.extension_name_snapshot or "")[:5]
        snap_full = _rebuild_full_name(fn, mn, ln, en)[:255]
        if (
            row.last_name_snapshot != ln
            or row.first_name_snapshot != fn
            or row.middle_name_snapshot != mn
            or row.extension_name_snapshot != en
            or row.full_name_snapshot != snap_full
        ):
            Archive.objects.filter(pk=row.pk).update(
                last_name_snapshot=ln,
                first_name_snapshot=fn,
                middle_name_snapshot=mn,
                extension_name_snapshot=en,
                full_name_snapshot=snap_full,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0041_applicant_form_queue_routed_fields"),
    ]

    operations = [
        migrations.RunPython(truncate_applicant_and_archive_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="applicant",
            name="extension_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Jr., Sr., II, III, IV, etc.",
                max_length=5,
                verbose_name="Extension Name",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="first_name",
            field=models.CharField(
                default="", max_length=15, verbose_name="First Name (Given Name)"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="last_name",
            field=models.CharField(
                default="", max_length=10, verbose_name="Last Name (Surname)"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="middle_name",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Middle Name"
            ),
        ),
        migrations.AlterField(
            model_name="archive",
            name="extension_name_snapshot",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name="archive",
            name="first_name_snapshot",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="archive",
            name="last_name_snapshot",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="archive",
            name="middle_name_snapshot",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
