# Generated by Django 5.2.10 on 2026-05-04 15:43

from django.db import migrations, models


def _rebuild_full_name(first_name, middle_name, last_name, extension_name):
    parts = [first_name or "", middle_name or "", last_name or ""]
    base = " ".join(p for p in parts if p).strip()
    if extension_name:
        full = f"{base}, {extension_name}".strip()
    else:
        full = base
    return (full or "")[:30]


def truncate_applicant_display_and_spouse_fields(apps, schema_editor):
    Applicant = apps.get_model("intake", "Applicant")
    Archive = apps.get_model("intake", "Archive")

    for row in Applicant.objects.all().iterator():
        pob = (row.place_of_birth or "")[:30]
        sn = (row.spouse_name or "")[:30]
        fn = _rebuild_full_name(
            row.first_name, row.middle_name, row.last_name, row.extension_name
        )
        if (
            row.place_of_birth != pob
            or row.spouse_name != sn
            or row.full_name != fn
        ):
            Applicant.objects.filter(pk=row.pk).update(
                place_of_birth=pob,
                spouse_name=sn,
                full_name=fn,
            )

    for row in Archive.objects.all().iterator():
        snap = (row.full_name_snapshot or "")[:30]
        if row.full_name_snapshot != snap:
            Archive.objects.filter(pk=row.pk).update(full_name_snapshot=snap)


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0042_shorten_applicant_and_archive_name_fields"),
    ]

    operations = [
        migrations.RunPython(truncate_applicant_display_and_spouse_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="applicant",
            name="full_name",
            field=models.CharField(
                editable=False, max_length=30, verbose_name="Full Name"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="place_of_birth",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Place of Birth"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="spouse_name",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Name of Spouse"
            ),
        ),
        migrations.AlterField(
            model_name="archive",
            name="full_name_snapshot",
            field=models.CharField(max_length=30),
        ),
    ]
