# Generated by Django 5.2.10 on 2026-05-04 15:56

from django.db import migrations, models


def truncate_occupation_and_household_full_names(apps, schema_editor):
    Applicant = apps.get_model("intake", "Applicant")
    HouseholdMember = apps.get_model("intake", "HouseholdMember")

    for row in Applicant.objects.exclude(occupation="").iterator():
        occ = (row.occupation or "")[:25]
        if row.occupation != occ:
            Applicant.objects.filter(pk=row.pk).update(occupation=occ)

    for row in HouseholdMember.objects.iterator():
        fn = (row.full_name or "")[:30]
        if row.full_name != fn:
            HouseholdMember.objects.filter(pk=row.pk).update(full_name=fn)


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0043_shorten_full_name_place_spouse_archive_snapshot"),
    ]

    operations = [
        migrations.RunPython(truncate_occupation_and_household_full_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="applicant",
            name="occupation",
            field=models.CharField(
                blank=True, max_length=25, verbose_name="Occupation"
            ),
        ),
        migrations.AlterField(
            model_name="householdmember",
            name="full_name",
            field=models.CharField(max_length=30, verbose_name="Full Name"),
        ),
    ]
