# Generated by Django 5.2.10 on 2026-05-04 15:59

from django.db import migrations, models


def truncate_danger_zone_and_project_fields(apps, schema_editor):
    Applicant = apps.get_model("intake", "Applicant")
    for row in Applicant.objects.iterator():
        loc = (row.danger_zone_location or "")[:30]
        pn = (row.project_name or "")[:30]
        if row.danger_zone_location != loc or row.project_name != pn:
            Applicant.objects.filter(pk=row.pk).update(
                danger_zone_location=loc,
                project_name=pn,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0044_shorten_occupation_and_household_member_name"),
    ]

    operations = [
        migrations.RunPython(truncate_danger_zone_and_project_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="applicant",
            name="danger_zone_location",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Specific Danger Zone Location"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="project_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Project that triggered relocation (road widening, drainage, government project, etc.).",
                max_length=30,
                verbose_name="Relocation Project Name",
            ),
        ),
    ]
