# Generated by Django 5.2.10 on 2026-05-12 18:49

from django.db import migrations


def remove_test_barangay(apps, schema_editor):
    Barangay = apps.get_model('intake', 'Barangay')
    Barangay.objects.filter(name='Test Barangay').delete()

class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0045_shorten_danger_zone_location_and_project_name"),
    ]

    operations = [
        migrations.RunPython(remove_test_barangay),
    ]
