# Generated by Django 5.2.10 on 2026-05-18 01:50

import django.core.validators
from django.conf import settings
from django.db import migrations, models


def clamp_years_residing_to_two_digits(apps, schema_editor):
    Applicant = apps.get_model('intake', 'Applicant')
    for row in Applicant.objects.exclude(years_residing__lte=99).iterator():
        row.years_residing = min(99, int(row.years_residing or 0))
        row.save(update_fields=['years_residing'])


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0046_remove_test_barangay"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(clamp_years_residing_to_two_digits, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="applicant",
            name="years_residing",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Whole years in Talisay City (2 digits maximum, 0–99).",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(99),
                ],
                verbose_name="Years Residing in Talisay",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicant",
            constraint=models.CheckConstraint(
                check=models.Q(("years_residing__lte", 99)),
                name="applicant_years_residing_max_99",
            ),
        ),
    ]
