# Generated by Django 5.2 on 2026-05-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0047_applicant_years_residing_two_digits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="householdmember",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("spouse", "Spouse"),
                    ("son", "Son"),
                    ("daughter", "Daughter"),
                    ("mother", "Mother"),
                    ("father", "Father"),
                    ("uncle", "Uncle"),
                    ("aunt", "Aunt"),
                    ("grandfather", "Grandfather"),
                    ("grandmother", "Grandmother"),
                    ("grandchild", "Grandchild"),
                    ("other", "Other Relative"),
                ],
                max_length=20,
                verbose_name="Relationship to Applicant",
            ),
        ),
    ]
