# Generated by Django 6.0.6 on 2026-08-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0051_applicant_civil_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="is_restored",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Set to True when applicant is restored from the archive list back to registration",
            ),
        ),
    ]
