# Generated by Django 6.0.3 on 2026-08-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0052_archive_is_restored"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="formally_archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Set to True when ARCHIVE record is clicked; removes from working list without Module 2 handoff",
            ),
        ),
    ]
