# Generated by Django 6.0.6 on 2026-09-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0053_add_formally_archived_to_archive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="ejection_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "— Select —"),
                    ("private_eviction", "Private Land Eviction"),
                    ("court_order", "Court Order"),
                    ("landowner_recovery", "Landowner Recovery"),
                    ("other", "Other"),
                ],
                default="",
                max_length=30,
                verbose_name="Ejection Type",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="household_size",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of household members as declared during registration",
                verbose_name="Household Size",
            ),
        ),
    ]
