# Generated by Django 6.0.6 on 2026-09-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0054_alter_applicant_ejection_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="doc_voter_cert",
            field=models.BooleanField(
                default=False, verbose_name="Voter's Certificate"
            ),
        ),
    ]
