# Generated by Django 6.0.6 on 2026-10-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0055_update_doc_voter_cert_verbose_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="is_registered_voter_talisay",
            field=models.BooleanField(
                default=False,
                help_text="Declared residency status in Talisay City.",
                verbose_name="Resident of Talisay City",
            ),
        ),
    ]
