# Generated by Django 6.0.6 on 2026-10-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0056_alter_applicant_is_registered_voter_talisay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="employment_status",
            field=models.CharField(
                choices=[
                    ("employed", "Employed"),
                    ("self_employed", "Self-Employed"),
                    ("unemployed", "Unemployed"),
                    ("retired", "Retired"),
                    ("other", "Other"),
                ],
                max_length=50,
                verbose_name="Status of Employment",
            ),
        ),
    ]
