# Generated by Django 6.0.6 on 2026-10-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0057_alter_applicant_employment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="last_name",
            field=models.CharField(
                default="", max_length=15, verbose_name="Last Name (Surname)"
            ),
        ),
        migrations.AlterField(
            model_name="archive",
            name="last_name_snapshot",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
