# Generated by Django 6.0.6 on 2026-10-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0058_increase_last_name_max_length_to_15"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="civil_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("widowed", "Widowed"),
                    ("divorced", "Divorced"),
                    ("separated", "Separated"),
                ],
                default="",
                max_length=20,
                verbose_name="Civil Status",
            ),
        ),
        migrations.AlterField(
            model_name="householdmember",
            name="civil_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("widowed", "Widowed"),
                    ("divorced", "Divorced"),
                    ("separated", "Separated"),
                ],
                default="single",
                max_length=20,
                verbose_name="Civil Status",
            ),
        ),
    ]
