# Generated by Django 6.0.3 on 2026-04-04 04:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("intake", "0002_seed_barangays"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Case Note",
                "verbose_name_plural": "Case Notes",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "case_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("boundary", "Boundary Dispute"),
                            ("structural", "Structural Issue"),
                            ("interpersonal", "Interpersonal Conflict"),
                            ("illegal_transfer", "Illegal Transfer"),
                            ("unauthorized", "Unauthorized Occupant"),
                            ("damage", "Property Damage"),
                            ("noise", "Noise/Disturbance"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigation", "Under Investigation"),
                            ("referred", "Referred to External Office"),
                            ("pending_decision", "Pending Decision"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed - No Action"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("complainant_name", models.CharField(max_length=255)),
                ("complainant_phone", models.CharField(blank=True, max_length=20)),
                ("subject_name", models.CharField(blank=True, max_length=255)),
                (
                    "received_at_location",
                    models.CharField(
                        choices=[
                            ("office", "THA Office"),
                            ("onsite", "On-site at Relocation Site"),
                        ],
                        default="office",
                        max_length=20,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "initial_description",
                    models.TextField(verbose_name="Complaint/Violation Description"),
                ),
                ("investigation_notes", models.TextField(blank=True)),
                ("investigated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "referred_to",
                    models.CharField(
                        blank=True,
                        help_text="E.g., City Engineering, OIC, Head",
                        max_length=100,
                    ),
                ),
                ("referred_at", models.DateTimeField(blank=True, null=True)),
                ("referral_notes", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "complainant_applicant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases_filed",
                        to="intake.applicant",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "investigated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases_investigated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Case",
                "verbose_name_plural": "Cases",
                "ordering": ["-received_at"],
            },
        ),
    ]
