# Generated by Django 6.0.3 on 2026-04-04 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("intake", "0002_seed_barangays"),
        ("units", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="related_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="units.housingunit",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="subject_applicant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases_against",
                to="intake.applicant",
            ),
        ),
        migrations.AddField(
            model_name="casenote",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="casenote",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="case_notes_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
