# Generated by Django 5.2.10 on 2026-04-22 17:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_initial"),
        ("intake", "0026_remove_queueentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipient_phone", models.CharField(max_length=20)),
                ("message_content", models.TextField()),
                (
                    "trigger_event",
                    models.CharField(
                        help_text="Event that triggered this SMS (case_filed, investigation_update, resolved, escalated, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True, help_text="SMS provider message ID", max_length=100
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases_sms_logs",
                        to="intake.applicant",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Log (Cases)",
                "verbose_name_plural": "SMS Logs (Cases)",
                "ordering": ["-sent_at"],
            },
        ),
    ]
