# Generated by Django 5.2.10 on 2026-05-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_spec_case_types_and_statuses"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SMSLog",
        ),
    ]
