# Generated by Django 5.2.10 on 2026-05-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0008_initial_description_max_100"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="case_type",
            field=models.CharField(
                choices=[
                    ("lot_boundary", "LOT BOUNDARY"),
                    ("noise", "NOISE COMPLAINT"),
                    ("drunk_disturbance", "DRUNK DISTURBANCE"),
                    ("community_quarrel", "COMMUNITY QUARREL"),
                    ("illegal_occupant", "ILLEGAL OCCUPANT CONCERN"),
                    ("occupancy_dispute", "OCCUPANCY DISPUTE"),
                    ("sanitation", "SANITATION COMPLAINT"),
                    ("other", "OTHER COMMUNITY CONCERN"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="CaseNote",
        ),
    ]
