# Generated by Django 5.2.10 on 2026-05-20 11:44

import re

from django.db import migrations, models

CASE_NUMBER_PATTERN = re.compile(r'^CASE-(\d{4})-(\d+)$')


def seed_case_year_sequences(apps, schema_editor):
    Case = apps.get_model('cases', 'Case')
    CaseYearSequence = apps.get_model('cases', 'CaseYearSequence')
    by_year = {}
    for case_number in Case.objects.values_list('case_number', flat=True):
        match = CASE_NUMBER_PATTERN.match(case_number or '')
        if match:
            year = int(match.group(1))
            num = int(match.group(2))
            by_year[year] = max(by_year.get(year, 0), num)
    for year, last_number in sorted(by_year.items()):
        CaseYearSequence.objects.update_or_create(
            year=year,
            defaults={'last_number': last_number},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0009_delete_casenote"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseYearSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(unique=True)),
                (
                    "last_number",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Last assigned sequence for this year; next case is last_number + 1.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case number sequence",
                "verbose_name_plural": "Case number sequences",
            },
        ),
        migrations.RunPython(seed_case_year_sequences, migrations.RunPython.noop),
    ]
