# Generated by Django 6.0.3 on 2026-05-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0015_settled_incident_log_complainant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_review", "Pending Review"),
                    ("under_review", "Under Review"),
                    ("mediation_monitoring", "Settlement"),
                    ("awaiting_response", "Awaiting Response"),
                    ("referred_engineering", "Awaiting Engineering Findings"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                default="pending_review",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="fieldreport",
            name="complaint_type",
            field=models.CharField(
                choices=[
                    ("lot_boundary", "LOT BOUNDARY"),
                    ("noise", "NOISE COMPLAINT"),
                    ("drunk_disturbance", "DRUNK DISTURBANCE"),
                    ("community_quarrel", "COMMUNITY QUARREL"),
                    ("illegal_occupant", "ILLEGAL OCCUPANT CONCERN"),
                    ("occupancy_dispute", "OCCUPANCY DISPUTE"),
                    ("sanitation", "SANITATION COMPLAINT"),
                    ("other", "OTHER COMMUNITY CONCERN"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fieldreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending staff review"),
                    ("accepted", "Accepted — case opened"),
                    ("dismissed", "Dismissed"),
                    ("clarification_requested", "Clarification requested"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="fieldsettledincidentlog",
            name="case_type",
            field=models.CharField(
                choices=[
                    ("lot_boundary", "LOT BOUNDARY"),
                    ("noise", "NOISE COMPLAINT"),
                    ("drunk_disturbance", "DRUNK DISTURBANCE"),
                    ("community_quarrel", "COMMUNITY QUARREL"),
                    ("illegal_occupant", "ILLEGAL OCCUPANT CONCERN"),
                    ("occupancy_dispute", "OCCUPANCY DISPUTE"),
                    ("sanitation", "SANITATION COMPLAINT"),
                    ("other", "OTHER COMMUNITY CONCERN"),
                ],
                max_length=20,
            ),
        ),
    ]
