# Generated by Django 5.2 on 2026-06-01 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0016_alter_case_status_alter_fieldreport_complaint_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fieldreport",
            name="case",
        ),
        migrations.RemoveField(
            model_name="fieldreport",
            name="related_unit",
        ),
        migrations.RemoveField(
            model_name="fieldreport",
            name="reviewed_by",
        ),
        migrations.RemoveField(
            model_name="fieldreport",
            name="ronda",
        ),
        migrations.RemoveField(
            model_name="fieldreport",
            name="subject_applicant",
        ),
        migrations.DeleteModel(
            name="CaseFieldUpdate",
        ),
        migrations.DeleteModel(
            name="FieldReport",
        ),
    ]
