# Generated by Django 6.0.6 on 2026-09-24 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0017_delete_unused_field_models"),
        ("intake", "0055_update_doc_voter_cert_verbose_name"),
        ("units", "0035_staticsettlement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["status", "-received_at"], name="cases_status_recv_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["-resolved_at"], name="cases_resolved_at_idx"),
        ),
    ]
