# Generated by Django 6.0.6 on 2026-09-24 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0018_case_desk_list_indexes"),
        ("intake", "0055_update_doc_voter_cert_verbose_name"),
        ("units", "0035_staticsettlement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="fieldsettledincidentlog",
            index=models.Index(fields=["-logged_at"], name="cases_settled_logged_idx"),
        ),
    ]
