# Generated by Django 6.0.3 on 2026-04-04 04:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0001_initial"),
        ("intake", "0002_seed_barangays"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HousingUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("block_number", models.CharField(max_length=10)),
                ("lot_number", models.CharField(max_length=10)),
                (
                    "area_sqm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Area (sq.m.)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("vacant", "Vacant - Available"),
                            ("occupied", "Occupied"),
                            ("notice_30", "Under Notice - 30 Days"),
                            ("notice_10", "Under Notice - 10 Days (Final)"),
                            ("repossessed", "Repossessed"),
                            ("maintenance", "Under Maintenance"),
                        ],
                        default="vacant",
                        max_length=20,
                    ),
                ),
                ("location_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Housing Unit",
                "verbose_name_plural": "Housing Units",
                "ordering": ["site", "block_number", "lot_number"],
            },
        ),
        migrations.CreateModel(
            name="LotAward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active - Occupying"),
                            ("transferred", "Properly Transferred"),
                            ("repossessed", "Repossessed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("awarded_at", models.DateTimeField()),
                (
                    "via_draw_lots",
                    models.BooleanField(
                        default=True, help_text="False if re-awarded repossessed unit"
                    ),
                ),
                ("draw_lots_date", models.DateField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("end_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lot_awards",
                        to="applications.application",
                    ),
                ),
                (
                    "awarded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lot_awards_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lot_awards",
                        to="units.housingunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lot Award",
                "verbose_name_plural": "Lot Awards",
                "ordering": ["-awarded_at"],
            },
        ),
        migrations.CreateModel(
            name="ElectricityConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending - Not Started"),
                            ("docs_submitted", "Documents Submitted to Negros Power"),
                            ("coordinating", "Coordination in Progress"),
                            ("approved", "Connection Approved"),
                            ("completed", "Connection Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("initiated_at", models.DateTimeField(blank=True, null=True)),
                ("docs_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("negros_power_reference", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="electricity_initiated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lot_award",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="electricity_connection",
                        to="units.lotaward",
                    ),
                ),
            ],
            options={
                "verbose_name": "Electricity Connection",
                "verbose_name_plural": "Electricity Connections",
            },
        ),
        migrations.CreateModel(
            name="ComplianceNotice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notice_type",
                    models.CharField(
                        choices=[
                            ("reminder_30", "Reminder Notice (30 Days)"),
                            ("final_10", "Final Notice (10 Days)"),
                            ("custom", "Custom Notice Period"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active - Awaiting Response"),
                            ("complied", "Complied - Resolved"),
                            ("escalated", "Escalated - No Response"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(verbose_name="Reason for Notice")),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "days_granted",
                    models.PositiveIntegerField(
                        help_text="Number of days before deadline",
                        verbose_name="Days to Comply",
                    ),
                ),
                ("deadline", models.DateField()),
                ("response_received_at", models.DateTimeField(blank=True, null=True)),
                ("response_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_decision", models.TextField(blank=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notice_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notices_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "response_received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responses_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_notices",
                        to="units.housingunit",
                    ),
                ),
                (
                    "lot_award",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_notices",
                        to="units.lotaward",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compliance Notice",
                "verbose_name_plural": "Compliance Notices",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="Blacklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("repossession", "Unit Repossessed - Non-Compliance"),
                            ("fraud", "Fraudulent Information"),
                            ("illegal_transfer", "Illegal Unit Transfer"),
                            ("other", "Other Violation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason_details", models.TextField(verbose_name="Detailed Reason")),
                ("blacklisted_at", models.DateTimeField(auto_now_add=True)),
                ("supporting_notes", models.TextField(blank=True)),
                (
                    "applicant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklist_record",
                        to="intake.applicant",
                    ),
                ),
                (
                    "blacklisted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blacklist_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "original_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blacklist_records",
                        to="units.housingunit",
                    ),
                ),
                (
                    "original_lot_award",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blacklist_records",
                        to="units.lotaward",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blacklist Entry",
                "verbose_name_plural": "Blacklist Entries",
            },
        ),
        migrations.CreateModel(
            name="RelocationSite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("address", models.TextField()),
                ("total_blocks", models.PositiveIntegerField(default=0)),
                ("total_lots", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "barangay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relocation_sites",
                        to="intake.barangay",
                    ),
                ),
                (
                    "caretaker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_sites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Relocation Site",
                "verbose_name_plural": "Relocation Sites",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OccupancyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("report_week_start", models.DateField()),
                ("report_week_end", models.DateField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reported_occupied", models.PositiveIntegerField(default=0)),
                ("reported_vacant", models.PositiveIntegerField(default=0)),
                ("reported_concerns", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted - Pending Review"),
                            ("confirmed", "Confirmed by Field Team"),
                            ("discrepancy", "Discrepancy Found"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_occupied",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "confirmed_vacant",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("discrepancy_notes", models.TextField(blank=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="occupancy_reports_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="occupancy_reports_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occupancy_reports",
                        to="units.relocationsite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Occupancy Report",
                "verbose_name_plural": "Occupancy Reports",
                "ordering": ["-report_week_start"],
            },
        ),
        migrations.AddField(
            model_name="housingunit",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="units.relocationsite",
            ),
        ),
        migrations.CreateModel(
            name="OccupancyReportDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reported_status",
                    models.CharField(
                        choices=[
                            ("occupied", "Occupied"),
                            ("unoccupied", "Unoccupied"),
                            ("concern", "Concern Noted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("concern_notes", models.TextField(blank=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="units.occupancyreport",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occupancy_report_details",
                        to="units.housingunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Occupancy Report Detail",
                "verbose_name_plural": "Occupancy Report Details",
                "ordering": ["report", "unit"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("report", "unit"), name="unique_unit_per_report"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="occupancyreport",
            constraint=models.UniqueConstraint(
                fields=("site", "report_week_start"),
                name="unique_weekly_report_per_site",
            ),
        ),
        migrations.AddConstraint(
            model_name="housingunit",
            constraint=models.UniqueConstraint(
                fields=("site", "block_number", "lot_number"),
                name="unique_unit_per_site",
            ),
        ),
    ]
