# Generated by Django 5.2.7 on 2026-04-11 21:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="housingunit",
            name="escalation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="housingunit",
            name="is_escalated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="housingunit",
            name="notice_date_issued",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="housingunit",
            name="notice_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="housingunit",
            name="notice_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("30-day", "30-day notice"),
                    ("10-day", "10-day final notice"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="housingunit",
            name="occupant_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="housingunit",
            name="occupant_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="housingunit",
            name="status",
            field=models.CharField(
                choices=[
                    ("Vacant — available", "Vacant — available"),
                    ("Occupied", "Occupied"),
                    ("Under notice (30-day)", "Under notice (30-day)"),
                    ("Final notice (10-day)", "Final notice (10-day)"),
                    ("Repossessed", "Repossessed"),
                    ("maintenance", "Under Maintenance"),
                ],
                default="Vacant — available",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="WeeklyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reported_status",
                    models.CharField(
                        choices=[
                            ("Occupied", "Occupied"),
                            ("Vacant", "Vacant"),
                            ("Concern", "Concern - Needs Follow-up"),
                        ],
                        max_length=50,
                    ),
                ),
                ("concern_notes", models.TextField(blank=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weekly_reports_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_report",
                        to="units.housingunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weekly Report",
                "verbose_name_plural": "Weekly Reports",
                "ordering": ["-last_updated"],
            },
        ),
    ]
