# Generated by Django 5.2.7 on 2026-04-15 00:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0002_housingunit_escalation_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "case_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("complainant_name", models.CharField(max_length=200)),
                (
                    "complainant_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Beneficiary Profile Reference",
                    ),
                ),
                (
                    "complaint_type",
                    models.CharField(
                        choices=[
                            ("Boundary Dispute", "Boundary Dispute"),
                            ("Structural Issue", "Structural Issue"),
                            ("Interpersonal Conflict", "Interpersonal Conflict"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("date_received", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open - Under Investigation"),
                            ("Referred", "Referred - Escalated"),
                            ("Resolved", "Resolved - Closed"),
                        ],
                        default="Open",
                        max_length=20,
                    ),
                ),
                (
                    "referred_to",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("City Engineering Office", "City Engineering Office"),
                            ("Field Officer", "Field Officer (Sir Russo)"),
                            ("Attorney", "Attorney"),
                            ("Head (Arthur)", "Head (Sir Arthur)"),
                            ("None", "— None —"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("referral_date", models.DateField(blank=True, null=True)),
                ("outcome", models.TextField(blank=True)),
                ("resolved_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases_handled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="units.relocationsite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case Record",
                "verbose_name_plural": "Case Records",
                "ordering": ["-date_received"],
            },
        ),
        migrations.CreateModel(
            name="CaseUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="units.caserecord",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="case_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Case Update",
                "verbose_name_plural": "Case Updates",
                "ordering": ["-updated_at"],
            },
        ),
    ]
