# Generated by Django 5.2.10 on 2026-05-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0006_remove_compliance_and_occupancy_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="electricityconnection",
            options={
                "verbose_name": "Electricity connection (unit / lot)",
                "verbose_name_plural": "Electricity connections (units)",
            },
        ),
    ]
