# Generated by Django 5.2.10 on 2026-05-06 06:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0007_electricity_connection_verbose_names"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstructionProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("site_clearing", "Site clearing"),
                            ("foundation", "Foundation"),
                            ("wall_framing", "Wall framing"),
                            ("roofing", "Roofing"),
                            ("finishing", "Finishing"),
                            ("completed", "Completed / Occupied"),
                        ],
                        default="not_started",
                        max_length=30,
                    ),
                ),
                ("percent_complete", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("expected_completion_date", models.DateField(blank=True, null=True)),
                ("last_inspected_at", models.DateTimeField(blank=True, null=True)),
                ("is_delayed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lot_award",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="construction_progress",
                        to="units.lotaward",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="construction_progress_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Construction progress",
                "verbose_name_plural": "Construction progress",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ConstructionProgressUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("site_clearing", "Site clearing"),
                            ("foundation", "Foundation"),
                            ("wall_framing", "Wall framing"),
                            ("roofing", "Roofing"),
                            ("finishing", "Finishing"),
                            ("completed", "Completed / Occupied"),
                        ],
                        max_length=30,
                    ),
                ),
                ("percent_complete", models.PositiveIntegerField()),
                ("visit_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="construction_progress_timeline_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="units.constructionprogress",
                    ),
                ),
            ],
            options={
                "verbose_name": "Construction progress update",
                "verbose_name_plural": "Construction progress updates",
                "ordering": ["-visit_date", "-created_at"],
            },
        ),
    ]
