# Generated by Django 5.2.10 on 2026-05-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0008_constructionprogress_constructionprogressupdate"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ElectricityConnection",
        ),
    ]
