# Generated by Django 5.2.10 on 2026-05-12 01:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0009_delete_electricityconnection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExplanationReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "beneficiary_explanation",
                    models.TextField(
                        blank=True,
                        help_text="Explanation provided by beneficiary for delay",
                    ),
                ),
                (
                    "explanation_submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When beneficiary submitted explanation",
                        null=True,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved — Extension Granted"),
                            ("denied", "Denied — Proceed to Final Notice"),
                            (
                                "needs_clarification",
                                "Needs Clarification — Request More Info",
                            ),
                        ],
                        default="pending_review",
                        max_length=30,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When staff reviewed explanation",
                        null=True,
                    ),
                ),
                (
                    "staff_decision_notes",
                    models.TextField(blank=True, help_text="Staff notes on decision"),
                ),
                (
                    "extension_approved",
                    models.BooleanField(
                        default=False, help_text="True if extension was approved"
                    ),
                ),
                (
                    "extension_months",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "1 Month"), (2, "2 Months"), (3, "3 Months")],
                        help_text="Duration of extension (if approved)",
                        null=True,
                    ),
                ),
                (
                    "extension_reason",
                    models.TextField(
                        blank=True,
                        help_text="Staff notes on why extension was approved/denied",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lot_award",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="explanation_reviews",
                        to="units.lotaward",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="THA Staff member who reviewed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="explanations_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="explanation_reviews",
                        to="units.housingunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Explanation Review",
                "verbose_name_plural": "Explanation Reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtensionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "extension_duration_months",
                    models.PositiveIntegerField(
                        choices=[(1, "1 Month"), (2, "2 Months"), (3, "3 Months")],
                        help_text="Duration of extension in months",
                    ),
                ),
                (
                    "extension_start_date",
                    models.DateField(help_text="When extension period begins"),
                ),
                (
                    "extension_end_date",
                    models.DateField(help_text="When extension period ends (deadline)"),
                ),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approval_notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes from staff on extension approval",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        help_text="Staff member who approved extension",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_extensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "explanation_review",
                    models.ForeignKey(
                        help_text="Explanation review that approved this extension",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_record",
                        to="units.explanationreview",
                    ),
                ),
                (
                    "lot_award",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extensions",
                        to="units.lotaward",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extension Record",
                "verbose_name_plural": "Extension Records",
                "ordering": ["-approved_at"],
            },
        ),
        migrations.CreateModel(
            name="MonitoringReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "occupancy_status",
                    models.CharField(
                        choices=[
                            ("properly_occupied", "Properly Occupied"),
                            ("temporarily_vacant", "Temporarily Vacant"),
                            ("unoccupied_abandoned", "Unoccupied / Abandoned"),
                        ],
                        help_text="Current occupancy condition",
                        max_length=30,
                    ),
                ),
                (
                    "people_observed",
                    models.CharField(
                        blank=True,
                        help_text="Number of people observed (e.g., '4', 'family of 3', 'none')",
                        max_length=100,
                    ),
                ),
                (
                    "occupancy_notes",
                    models.TextField(
                        blank=True, help_text="Observations about occupancy condition"
                    ),
                ),
                (
                    "construction_status",
                    models.CharField(
                        choices=[
                            ("no_structure", "No Structure"),
                            ("site_clearing", "Site Clearing"),
                            ("foundation", "Foundation"),
                            ("wall_framing", "Wall Framing"),
                            ("roofing", "Roofing"),
                            ("finishing", "Finishing"),
                            ("completed_occupied", "Completed / Occupied"),
                        ],
                        help_text="Current construction stage",
                        max_length=30,
                    ),
                ),
                (
                    "percent_complete",
                    models.PositiveIntegerField(
                        default=0, help_text="Estimated construction progress (0-100%)"
                    ),
                ),
                (
                    "progress_notes",
                    models.TextField(
                        blank=True, help_text="Details about construction progress"
                    ),
                ),
                (
                    "general_remarks",
                    models.TextField(
                        blank=True,
                        help_text="Overall assessment and remarks from caretaker",
                    ),
                ),
                (
                    "is_complete",
                    models.BooleanField(
                        default=True, help_text="True if all required fields are filled"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lot_award",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_reports",
                        to="units.lotaward",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        help_text="Caretaker/Ronda who submitted report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monitoring_reports_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_reports",
                        to="units.housingunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monitoring Report",
                "verbose_name_plural": "Monitoring Reports",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddField(
            model_name="explanationreview",
            name="triggered_by_report",
            field=models.ForeignKey(
                blank=True,
                help_text="MonitoringReport that triggered this explanation review",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triggered_explanations",
                to="units.monitoringreport",
            ),
        ),
        migrations.CreateModel(
            name="MonitoringTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("day_15_inspection", "Day 15 Inspection"),
                            ("day_30_inspection", "Day 30 Inspection"),
                            ("month_1_inspection", "Extension Month 1 — Inspection"),
                            ("month_2_inspection", "Extension Month 2 — Inspection"),
                            ("month_3_inspection", "Extension Month 3 — Inspection"),
                            ("final_inspection", "Final Inspection (Post-Notice)"),
                        ],
                        help_text="Type of monitoring task",
                        max_length=30,
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        help_text="When task was scheduled (creation date)"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(help_text="Deadline for completing task"),
                ),
                (
                    "days_from_award",
                    models.PositiveIntegerField(
                        help_text="Number of days from award date (15, 30, 60, 90, final)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When task was completed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Caretaker or Ronda assigned to this task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_monitoring_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lot_award",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_tasks",
                        to="units.lotaward",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_tasks",
                        to="units.housingunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monitoring Task",
                "verbose_name_plural": "Monitoring Tasks",
                "ordering": ["due_date", "task_type"],
            },
        ),
        migrations.AddField(
            model_name="monitoringreport",
            name="task",
            field=models.ForeignKey(
                help_text="Monitoring task this report fulfills",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="units.monitoringtask",
            ),
        ),
        migrations.CreateModel(
            name="OccupancyMonitoringCycle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cycle_stage",
                    models.CharField(
                        choices=[
                            ("original_30_day", "Original 30-Day Monitoring"),
                            ("extension_month_1", "Extension Month 1"),
                            ("extension_month_2", "Extension Month 2"),
                            ("extension_month_3", "Extension Month 3"),
                            ("final_notice_30_day", "Final Notice — 30 Days"),
                        ],
                        default="original_30_day",
                        help_text="Current monitoring stage in the lifecycle",
                        max_length=30,
                    ),
                ),
                (
                    "stage_start_date",
                    models.DateField(help_text="When this stage begins"),
                ),
                (
                    "stage_end_date",
                    models.DateField(help_text="When this stage ends (deadline)"),
                ),
                (
                    "days_allowed",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Number of days allowed for this stage (30 for original, varies for extension)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="True if this is the current active cycle",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lot_award",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_cycles",
                        to="units.lotaward",
                    ),
                ),
            ],
            options={
                "verbose_name": "Occupancy Monitoring Cycle",
                "verbose_name_plural": "Occupancy Monitoring Cycles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="explanationreview",
            index=models.Index(
                fields=["review_status", "-created_at"],
                name="units_expla_review__96f981_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="explanationreview",
            index=models.Index(
                fields=["lot_award", "review_status"],
                name="units_expla_lot_awa_822c69_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monitoringtask",
            index=models.Index(
                fields=["assigned_to", "status", "due_date"],
                name="units_monit_assigne_4684c6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monitoringtask",
            index=models.Index(
                fields=["lot_award", "status"], name="units_monit_lot_awa_61fa56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monitoringreport",
            index=models.Index(
                fields=["lot_award", "-submitted_at"],
                name="units_monit_lot_awa_903091_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monitoringreport",
            index=models.Index(
                fields=["occupancy_status", "construction_status"],
                name="units_monit_occupan_b9645c_idx",
            ),
        ),
    ]
