# Generated by Django 5.2.10 on 2026-05-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0016_monitoringreport_ongoing_construction_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="explanationreview",
            name="deadline_due_sms_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the past-deadline / non-compliance notice SMS was sent",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="explanationreview",
            name="deadline_eve_sms_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the day-before deadline reminder SMS was sent",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="explanationreview",
            name="letter_deadline_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date/time by which the beneficiary must submit an explanation letter on file",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="explanationreview",
            name="letter_document",
            field=models.FileField(
                blank=True,
                help_text="Scanned or uploaded explanation letter (staff)",
                upload_to="explanation_letters/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="explanationreview",
            name="letter_received_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When staff recorded receipt of the explanation letter",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="explanationreview",
            name="trigger_kind",
            field=models.CharField(
                choices=[
                    ("staff_no_progress", "Staff marked monitoring as No Progress"),
                    ("auto_rule", "Automated monitoring evaluation rule"),
                ],
                default="staff_no_progress",
                help_text="Whether this case was opened by staff assessment or automated rules",
                max_length=30,
            ),
        ),
    ]
