# Generated by Django 5.2.10 on 2026-05-16 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0018_day30_inspection_thirty_days_after_day15"),
    ]

    operations = [
        migrations.AlterField(
            model_name="housingunit",
            name="block_number",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d+$", message="Must be digits only (0-9)."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="housingunit",
            name="lot_number",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d+$", message="Must be digits only (0-9)."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="monitoringtask",
            name="days_from_award",
            field=models.PositiveIntegerField(
                help_text="Monitoring day after the 30-day possession grace period when the visit is due (15 for the first visit; 45 for the final 30 Day visit, i.e. 30 days after the 15 Day due date)."
            ),
        ),
    ]
