# Generated by Django 6.0.3 on 2026-05-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0020_monitoring_60_day_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitoringtask",
            name="days_from_award",
            field=models.PositiveIntegerField(
                help_text="Monitoring day after the 30-day possession grace period when the visit is due (60 for the first visit; 90 for the final 30 Day visit, i.e. 30 days after the 60 Day due date)."
            ),
        ),
        migrations.AlterField(
            model_name="monitoringtask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("day_15_inspection", "Day 60 Inspection"),
                    ("day_30_inspection", "Day 30 Inspection"),
                    ("month_1_inspection", "Extension Month 1 — Inspection"),
                    ("month_2_inspection", "Extension Month 2 — Inspection"),
                    ("month_3_inspection", "Extension Month 3 — Inspection"),
                    ("final_inspection", "Final Inspection (Post-Notice)"),
                ],
                help_text="Type of monitoring task",
                max_length=30,
            ),
        ),
    ]
