# Generated by Django 5.2 on 2026-06-01 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0024_final_visit_120_days_after_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WeeklyReport",
        ),
    ]
