# Generated by Django 5.2 on 2026-06-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0025_delete_weeklyreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occupancymonitoringcycle",
            name="cycle_stage",
            field=models.CharField(
                choices=[
                    ("original_30_day", "Original 30-Day Monitoring"),
                    ("extension_month_1", "Extension Month 1"),
                    ("extension_month_2", "Extension Month 2"),
                    ("extension_month_3", "Extension Month 3"),
                    ("final_notice_30_day", "Final Notice — 90 Days"),
                ],
                default="original_30_day",
                help_text="Current monitoring stage in the lifecycle",
                max_length=30,
            ),
        ),
    ]
