# Generated by Django 6.0.6 on 2026-07-11 12:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0029_housingunit_plan_polygon_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lotaward",
            name="authenticated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the lot award document was authenticated",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lotaward",
            name="authenticated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member (2nd/4th member) who authenticated the lot award document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lot_awards_authenticated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="LotAwardDocumentValidation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when validation was recorded",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional remarks about this validation event",
                    ),
                ),
                (
                    "lot_award",
                    models.ForeignKey(
                        help_text="The lot award whose document was validated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_validations",
                        to="units.lotaward",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        help_text="Staff member who validated the document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lot_award_validations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lot Award Document Validation",
                "verbose_name_plural": "Lot Award Document Validations",
                "ordering": ["-validated_at"],
            },
        ),
    ]
