# Generated by Django 6.0.6 on 2026-09-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0030_lot_award_authentication_and_validation_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="relocationsite",
            name="map_phase",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Phase 1 (Blocks 1–12)"), (2, "Phase 2 (Blocks 13–21)")],
                default=1,
                help_text="Which lot-plan map overlay to display for this site.",
            ),
        ),
    ]
