# Generated by Django 6.0.6 on 2026-09-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0031_add_map_phase_to_relocation_site"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="housingunit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("plan_polygon_index__isnull", False)),
                fields=("site", "plan_polygon_index"),
                name="unique_plan_polygon_per_site",
            ),
        ),
    ]
