# Generated by Django 6.0.6 on 2026-09-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0032_unique_plan_polygon_per_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relocationsite",
            name="map_phase",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Phase 1")],
                default=1,
                help_text="Lot-plan map overlay for this site (Phase 1 only).",
            ),
        ),
    ]
