# Generated by Django 6.0.6 on 2026-09-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0033_alter_relocationsite_map_phase_phase1_only"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relocationsite",
            name="map_phase",
        ),
    ]
