# Generated by Django 6.0.6 on 2026-09-23 16:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0034_remove_relocationsite_map_phase"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticSettlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Display number starting at 2 (Settlement 1 is reserved for the live map).",
                        unique=True,
                        validators=[django.core.validators.MinValueValidator(2)],
                    ),
                ),
                ("image", models.ImageField(upload_to="settlements/%Y/%m/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="static_settlements_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Static Settlement",
                "verbose_name_plural": "Static Settlements",
                "ordering": ["number"],
            },
        ),
    ]
