# Generated by Django 5.2.7 on 2026-04-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("head", "First Member — Head"),
                    ("oic", "OIC-THA (Officer-in-Charge)"),
                    ("second_member", "Second Member"),
                    ("fourth_member", "Fourth Member"),
                    ("fifth_member", "Fifth Member"),
                    ("caretaker", "Caretaker"),
                    ("ronda", "Ronda (Field Personnel)"),
                    ("field", "Field Personnel"),
                ],
                help_text="Staff position in THA organizational structure",
                max_length=50,
            ),
        ),
    ]
