# Generated by Django 6.0.3 on 2026-04-04 04:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0001_initial"),
        ("intake", "0002_seed_barangays"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("barangay_residency", "Barangay Certificate of Residency"),
                            ("barangay_indigency", "Barangay Certificate of Indigency"),
                            ("cedula", "Cedula (Community Tax Certificate)"),
                            ("police_clearance", "Police Clearance"),
                            ("no_property", "Certificate of No Property"),
                            ("photo_2x2", "2x2 Picture"),
                            ("house_sketch", "Sketch of House Location"),
                            ("application_form", "Application Form"),
                            ("notarized_docs", "Notarized Documents"),
                            ("engineering_assessment", "Engineering Assessment"),
                            (
                                "signed_application",
                                "Signed Application (Head-Approved)",
                            ),
                            ("lot_award", "Lot Award Document"),
                            ("electricity_app", "Electricity Connection Application"),
                            ("cdrrmo_cert", "CDRRMO Certification"),
                            ("explanation_letter", "Explanation Letter"),
                            ("other", "Other Document"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="documents/%Y/%m/")),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="intake.applicant",
                    ),
                ),
                (
                    "requirement_submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="applications.requirementsubmission",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["applicant", "document_type"],
                        name="documents_d_applica_4a8ead_idx",
                    ),
                    models.Index(
                        fields=["document_type"], name="documents_d_documen_40c475_idx"
                    ),
                ],
            },
        ),
    ]
