# Generated by Django 5.2.10 on 2026-04-24 01:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_remove_facilitatedservice_application_and_more"),
        ("documents", "0002_smslog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectricityConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending - Not Yet Applied"),
                            ("applied", "Applied to Negros Power"),
                            ("inspection_scheduled", "Inspection Scheduled"),
                            ("inspection_completed", "Inspection Completed"),
                            ("connected", "Electricity Connected"),
                            ("issues", "Issues - Requires Follow-up"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("negros_power_reference", models.CharField(blank=True, max_length=50)),
                ("inspection_date", models.DateField(blank=True, null=True)),
                ("inspection_result", models.TextField(blank=True)),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                ("meter_number", models.CharField(blank=True, max_length=50)),
                ("issue_description", models.TextField(blank=True)),
                ("issue_resolved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="electricity_connection",
                        to="applications.application",
                    ),
                ),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="electricity_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Electricity Connection",
                "verbose_name_plural": "Electricity Connections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LotAwarding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lot_number", models.CharField(max_length=50)),
                ("block_number", models.CharField(blank=True, max_length=50)),
                (
                    "site_name",
                    models.CharField(
                        blank=True, help_text="e.g., GK Cabatangan", max_length=100
                    ),
                ),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                ("contract_signed", models.BooleanField(default=False)),
                ("contract_signed_at", models.DateTimeField(blank=True, null=True)),
                ("keys_turned_over", models.BooleanField(default=False)),
                ("keys_turned_over_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lot_awarding",
                        to="applications.application",
                    ),
                ),
                (
                    "awarded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lots_awarded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lot Awarding",
                "verbose_name_plural": "Lot Awardings",
                "ordering": ["-awarded_at"],
            },
        ),
        migrations.CreateModel(
            name="FacilitatedService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("notarial", "Notarial Services"),
                            ("engineering", "Engineering Assessment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilitated_services",
                        to="applications.application",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Facilitated Service",
                "verbose_name_plural": "Facilitated Services",
                "ordering": ["application", "service_type"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("application", "service_type"),
                        name="unique_application_service_docs",
                    )
                ],
            },
        ),
    ]
