# Generated by Django 5.2.10 on 2026-04-25 03:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0010_remove_hard_moved_requirement_models"),
        ("documents", "0004_hard_move_requirements_and_routing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitteeInterview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("follow_up", "Needs Follow-up"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result_recorded_at", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="committee_interview",
                        to="applications.application",
                    ),
                ),
                (
                    "result_recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="committee_interviews_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scheduled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="committee_interviews_scheduled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Committee Interview",
                "verbose_name_plural": "Committee Interviews",
                "ordering": ["-result_recorded_at", "-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="FieldInspection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("findings", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted by Ronda"),
                            ("confirmed", "Confirmed by THA Staff"),
                            ("needs_revision", "Needs Revision"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("staff_notes", models.TextField(blank=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_inspection",
                        to="applications.application",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="THA Staff who confirmed the report.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_inspections_confirmed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        help_text="Ronda user who submitted the field report.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_inspections_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Inspection",
                "verbose_name_plural": "Field Inspections",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="FieldInspectionPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="documents/field_inspection/%Y/%m/"),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="documents.fieldinspection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Inspection Photo",
                "verbose_name_plural": "Field Inspection Photos",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="EndorsementRoutingStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("barangay_affairs", "Barangay Affairs Office endorsement"),
                            (
                                "community_relations",
                                "Community Relations Office endorsement",
                            ),
                            (
                                "cswd_referral",
                                "CSWD referral, interview, and profiling",
                            ),
                            ("sp_endorsement", "SP endorsement"),
                            ("gk_orientation", "GK team orientation and conformity"),
                            ("tha_recommending", "THA recommending approval"),
                            ("mayor_final", "Mayor's Office final approval"),
                        ],
                        max_length=40,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endorsement_routing_steps",
                        to="applications.application",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="endorsement_steps_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Endorsement Routing Step",
                "verbose_name_plural": "Endorsement Routing Steps",
                "ordering": ["application", "step"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("application", "step"),
                        name="unique_application_endorsement_step",
                    )
                ],
            },
        ),
    ]
