# Generated by Django 5.2.10 on 2026-04-28 05:37

from django.db import migrations, models


def forwards_set_default_vault_types(apps, schema_editor):
    """Backfill Group A vault links for seeded codes (stored in Requirement rows, not in application code paths)."""
    Requirement = apps.get_model("documents", "Requirement")
    backfill_by_code = (
        ("R01", "barangay_residency"),
        ("R02", "barangay_indigency"),
        ("R03", "cedula"),
        ("R04", "police_clearance"),
        ("R05", "no_property"),
        ("R06", "photo_2x2"),
        ("R07", "house_sketch"),
    )
    for code, vt in backfill_by_code:
        Requirement.objects.filter(code=code, vault_document_type="").update(vault_document_type=vt)


def noop_reverse_forward_set(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_remove_head_routing_steps"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirement",
            name="vault_document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("barangay_residency", "Barangay Certificate of Residency"),
                    ("barangay_indigency", "Barangay Certificate of Indigency"),
                    ("cedula", "Cedula (Community Tax Certificate)"),
                    ("police_clearance", "Police Clearance"),
                    ("no_property", "Certificate of No Property"),
                    ("photo_2x2", "2x2 Picture"),
                    ("house_sketch", "Sketch of House Location"),
                    ("application_form", "Application Form"),
                    ("notarized_docs", "Notarized Documents"),
                    ("engineering_assessment", "Engineering Assessment"),
                    ("signed_application", "Signed Application (Head-Approved)"),
                    ("lot_award", "Lot Award Document"),
                    ("electricity_app", "Electricity Connection Application"),
                    ("cdrrmo_cert", "CDRRMO Certification"),
                    ("explanation_letter", "Explanation Letter"),
                    ("other", "Other Document"),
                ],
                default="",
                help_text="Links this row to vault uploads: a scan exists when Applicant has a Document with this type.",
                max_length=30,
            ),
        ),
        migrations.RunPython(forwards_set_default_vault_types, noop_reverse_forward_set),
    ]
