# Generated by Django 5.2.10 on 2026-04-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_requirement_vault_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("barangay_residency", "Barangay Certificate of Residency"),
                    ("barangay_indigency", "Barangay Certificate of Indigency"),
                    ("cedula", "Cedula (Community Tax Certificate)"),
                    ("police_clearance", "Police Clearance"),
                    ("no_property", "Certificate of No Property"),
                    ("photo_2x2", "2x2 Picture"),
                    ("house_sketch", "Sketch of House Location"),
                    (
                        "isf_situational_docs",
                        "ISF situational documentation (Applicant Situation Options A/B/C)",
                    ),
                    ("application_form", "Application Form"),
                    ("notarized_docs", "Notarized Documents"),
                    ("engineering_assessment", "Engineering Assessment"),
                    ("signed_application", "Signed Application (Head-Approved)"),
                    ("lot_award", "Lot Award Document"),
                    ("electricity_app", "Electricity Connection Application"),
                    ("cdrrmo_cert", "CDRRMO Certification"),
                    ("explanation_letter", "Explanation Letter"),
                    ("other", "Other Document"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="vault_document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("barangay_residency", "Barangay Certificate of Residency"),
                    ("barangay_indigency", "Barangay Certificate of Indigency"),
                    ("cedula", "Cedula (Community Tax Certificate)"),
                    ("police_clearance", "Police Clearance"),
                    ("no_property", "Certificate of No Property"),
                    ("photo_2x2", "2x2 Picture"),
                    ("house_sketch", "Sketch of House Location"),
                    (
                        "isf_situational_docs",
                        "ISF situational documentation (Applicant Situation Options A/B/C)",
                    ),
                    ("application_form", "Application Form"),
                    ("notarized_docs", "Notarized Documents"),
                    ("engineering_assessment", "Engineering Assessment"),
                    ("signed_application", "Signed Application (Head-Approved)"),
                    ("lot_award", "Lot Award Document"),
                    ("electricity_app", "Electricity Connection Application"),
                    ("cdrrmo_cert", "CDRRMO Certification"),
                    ("explanation_letter", "Explanation Letter"),
                    ("other", "Other Document"),
                ],
                default="",
                help_text="Links this row to vault uploads: a scan exists when Applicant has a Document with this type.",
                max_length=30,
            ),
        ),
    ]
