# Generated by Django 5.2.10 on 2026-05-02 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0010_document_incident_report_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="documents/%Y/%m/"),
        ),
        migrations.CreateModel(
            name="DocumentBlob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.BinaryField()),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blob_record",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document blob",
                "verbose_name_plural": "Document blobs",
            },
        ),
    ]
