# Generated by Django 5.2.10 on 2026-05-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_documentblob_and_nullable_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FacilitatedService",
        ),
    ]
