# Generated by Django 5.2.10 on 2026-05-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0013_alter_document_document_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="electricityconnection",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Electricity connection (application)",
                "verbose_name_plural": "Electricity connections (applications)",
            },
        ),
    ]
