# Generated by Django 5.2.10 on 2026-05-07 16:20

from django.db import migrations, models


def remap_legacy_electricity_document_type(apps, schema_editor):
    Document = apps.get_model("documents", "Document")
    Document.objects.filter(document_type="electricity_app").update(document_type="other")


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0014_electricity_connection_verbose_names"),
    ]

    operations = [
        migrations.RunPython(
            remap_legacy_electricity_document_type,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("barangay_residency", "Barangay Certificate of Residency"),
                    ("barangay_indigency", "Barangay Certificate of Indigency"),
                    ("cedula", "Cedula (Community Tax Certificate)"),
                    ("police_clearance", "Police Clearance"),
                    ("no_property", "Certificate of No Property"),
                    ("photo_2x2", "2x2 Picture"),
                    ("house_sketch", "Sketch of House Location"),
                    (
                        "voter_certification",
                        "Voter Certification (COMELEC / Barangay voter record)",
                    ),
                    (
                        "isf_situational_docs",
                        "ISF situational documentation (Applicant Situation Options A/B/C)",
                    ),
                    ("application_form", "Application Form"),
                    ("notarized_docs", "Notarized Documents"),
                    ("engineering_assessment", "Engineering Assessment"),
                    ("signed_application", "Physically signed application (scan)"),
                    ("lot_award", "Lot Award Document"),
                    ("cdrrmo_cert", "CDRRMO Certification"),
                    ("incident_report", "Incident report"),
                    ("explanation_letter", "Explanation Letter"),
                    ("other", "Other Document"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="vault_document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("barangay_residency", "Barangay Certificate of Residency"),
                    ("barangay_indigency", "Barangay Certificate of Indigency"),
                    ("cedula", "Cedula (Community Tax Certificate)"),
                    ("police_clearance", "Police Clearance"),
                    ("no_property", "Certificate of No Property"),
                    ("photo_2x2", "2x2 Picture"),
                    ("house_sketch", "Sketch of House Location"),
                    (
                        "voter_certification",
                        "Voter Certification (COMELEC / Barangay voter record)",
                    ),
                    (
                        "isf_situational_docs",
                        "ISF situational documentation (Applicant Situation Options A/B/C)",
                    ),
                    ("application_form", "Application Form"),
                    ("notarized_docs", "Notarized Documents"),
                    ("engineering_assessment", "Engineering Assessment"),
                    ("signed_application", "Physically signed application (scan)"),
                    ("lot_award", "Lot Award Document"),
                    ("cdrrmo_cert", "CDRRMO Certification"),
                    ("incident_report", "Incident report"),
                    ("explanation_letter", "Explanation Letter"),
                    ("other", "Other Document"),
                ],
                default="",
                help_text="Links this row to vault uploads: a scan exists when Applicant has a Document with this type.",
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="ElectricityConnection",
        ),
    ]
