# Generated by Django 6.0.6 on 2026-08-02 14:04

from django.db import migrations


def reorder_requirements(apps, schema_editor):
    Requirement = apps.get_model("documents", "Requirement")
    
    # Define the desired alphabetical order mapping (code -> new order)
    order_mapping = {
        'R06': 1, # 2x2 Picture
        'R02': 2, # Brgy. Certificate of Indigency
        'R01': 3, # Brgy. Certificate of Residency
        'R03': 4, # Cedula
        'R05': 5, # Certificate of No Property
        'R04': 6, # Police Clearance
        'R07': 7, # Sketch of House Location
        'RVT': 8, # Voter Certification
    }
    
    for code, new_order in order_mapping.items():
        Requirement.objects.filter(code=code).update(order=new_order)

def revert_reorder(apps, schema_editor):
    Requirement = apps.get_model("documents", "Requirement")
    
    # Original order from seed
    order_mapping = {
        'R01': 1,
        'R02': 2,
        'R03': 3,
        'R04': 4,
        'R05': 5,
        'R06': 6,
        'R07': 7,
        'RVT': 99,
    }
    
    for code, new_order in order_mapping.items():
        Requirement.objects.filter(code=code).update(order=new_order)


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0025_update_rvt_requirement_name"),
    ]

    operations = [
        migrations.RunPython(reorder_requirements, revert_reorder),
    ]
