"""
Django settings for talisay_housing project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env — override=True so local .env wins over stale SMS_SERVICE=console shell exports.
load_dotenv(BASE_DIR / '.env', override=True)


def _env_bool(key: str, default: bool = False) -> bool:
    v = os.environ.get(key)
    if v is None:
        return default
    return v.strip().lower() in ('1', 'true', 'yes', 'on')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-l#!1!(warwnj*ld=dz=-kd13sfzq1s9m460mt8w^p3l4+0##lg"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# When True, staff housing monitoring UI does not block extension 30 Day (month_2) on the
# caretaker midpoint—Confirm / Inspection details / Notify flow works for QA. Set env
# EXTENSION_30DAY_SKIP_MIDPOINT_BLOCK=0 on production. Defaults to DEBUG.
EXTENSION_30DAY_SKIP_MIDPOINT_BLOCK = _env_bool(
    'EXTENSION_30DAY_SKIP_MIDPOINT_BLOCK',
    default=DEBUG,
)

ALLOWED_HOSTS = ['*']  # Allow all hosts for development/testing


# Application definition

INSTALLED_APPS = [
    # Jazzmin admin (must be before django.contrib.admin)
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "django.contrib.sites",
    # Third-party
    'widget_tweaks',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    # Local apps
    'accounts',
    'intake',
    'applications',
    'documents',
    'units',
    'cases',
    'dashboard',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
]
if DEBUG:
    MIDDLEWARE.append("accounts.middleware.LocalhostCanonicalizationMiddleware")
MIDDLEWARE += [
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "talisay_housing.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "talisay_housing.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "talisay_housing_db",
        "USER": "postgres",
        "PASSWORD": "1234",
        "HOST": "localhost",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Manila"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (User uploads)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Login/Logout URLs
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'accounts:dashboard'
LOGOUT_REDIRECT_URL = 'accounts:dashboard'

# Session settings
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 60 * 60 * 5  # 5 hours

# =============================================================================
# Google OAuth (staff portals via django-allauth)
# =============================================================================
GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '').strip()
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get('GOOGLE_OAUTH_CLIENT_SECRET', '').strip()
_domains_raw = os.environ.get('GOOGLE_OAUTH_ALLOWED_DOMAINS', '').strip()
if _domains_raw:
    GOOGLE_OAUTH_ALLOWED_DOMAINS = tuple(
        d.strip().lower().lstrip('@') for d in _domains_raw.split(',') if d.strip()
    )
elif os.environ.get('GOOGLE_OAUTH_ALLOWED_DOMAIN', '').strip():
    GOOGLE_OAUTH_ALLOWED_DOMAINS = (
        os.environ.get('GOOGLE_OAUTH_ALLOWED_DOMAIN', '').strip().lower().lstrip('@'),
    )
else:
    # Default: personal Gmail + THA Workspace accounts
    GOOGLE_OAUTH_ALLOWED_DOMAINS = ('gmail.com', 'talisayhousing.gov.ph')

ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_LOGIN_METHODS = {'username'}
ACCOUNT_SIGNUP_FIELDS = ['email', 'username*', 'password1*', 'password2*']
SOCIALACCOUNT_AUTO_SIGNUP = False
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.THASocialAccountAdapter'
# Skip the intermediate "Sign In Via Google" confirmation page — go straight to Google.
SOCIALACCOUNT_LOGIN_ON_GET = True
# Credentials live in DB (python manage.py setup_google_oauth) — do not duplicate APP here.
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
}

# =============================================================================
# SMS — Semaphore (Philippines)
# =============================================================================
# SMS_SERVICE: console | semaphore
# Live sending requires SEMAPHORE_API_KEY from https://semaphore.co/

SMS_ENABLED = _env_bool('SMS_ENABLED', default=True)
SMS_SERVICE = os.environ.get('SMS_SERVICE', 'console').strip().lower()

SEMAPHORE_API_KEY = os.environ.get('SEMAPHORE_API_KEY', '').strip()
SEMAPHORE_SENDER_NAME = os.environ.get('SEMAPHORE_SENDER_NAME', '').strip()
# Priority queue bypasses Semaphore's standard FIFO backlog (2 credits/SMS). Recommended for staff alerts.
SEMAPHORE_USE_PRIORITY_QUEUE = _env_bool('SEMAPHORE_USE_PRIORITY_QUEUE', default=True)
SEMAPHORE_SEND_TIMEOUT_SECONDS = float(os.environ.get('SEMAPHORE_SEND_TIMEOUT_SECONDS', '12'))
SEMAPHORE_SEND_RETRY_ATTEMPTS = int(os.environ.get('SEMAPHORE_SEND_RETRY_ATTEMPTS', '2'))
SEMAPHORE_SEND_RETRY_BACKOFF_SECONDS = float(os.environ.get('SEMAPHORE_SEND_RETRY_BACKOFF_SECONDS', '1.0'))

if SMS_SERVICE == 'semaphore' and SEMAPHORE_API_KEY:
    _sms_queue = 'priority' if SEMAPHORE_USE_PRIORITY_QUEUE else 'standard'
    _sms_boot = (
        f'live Semaphore ({_sms_queue} queue, sender: {SEMAPHORE_SENDER_NAME or "account default"})'
    )
elif SMS_SERVICE == 'console':
    _sms_boot = 'console simulation — no real SMS (set SMS_SERVICE=semaphore in .env for live sends)'
else:
    _sms_boot = f'{SMS_SERVICE!r} (check SMS_SERVICE / SEMAPHORE_API_KEY in .env)'
import sys as _sys  # noqa: E402

_sys.stderr.write(f'\n[IHSMS] SMS mode: {_sms_boot}. Restart runserver after any .env change.\n\n')
_sys.stderr.flush()
# =============================================================================
# Jazzmin Admin Configuration
# =============================================================================
JAZZMIN_SETTINGS = {
    # Title & branding
    "site_title": "IHSMS Admin",
    "site_header": "Talisay City Housing Authority",
    "site_brand": "IHSMS",
    "welcome_sign": "Integrated Housing Services and Monitoring System — Talisay City Housing Authority",
    "login_logo": None,

    # UI customization
    "show_ui_builder": True,  # Allow live UI customization
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [],

    # Icons
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "intake": "fas fa-inbox",
        "intake.Applicant": "fas fa-user-check",
        "intake.Barangay": "fas fa-map-marker",
        "units.Blacklist": "fas fa-ban",
        "intake.CDRRMOCertification": "fas fa-certificate",
        "intake.HouseholdMember": "fas fa-users",
        "intake.QueueEntry": "fas fa-list-ol",
        "intake.SMSLog": "fas fa-sms",
        "applications": "fas fa-file-alt",
        "applications.Application": "fas fa-file-contract",
        "documents.Requirement": "fas fa-checklist",
        "documents.RequirementSubmission": "fas fa-check-circle",
        "documents": "fas fa-folder",
        "documents.Document": "fas fa-file",
        "units": "fas fa-building",
        "units.HousingUnit": "fas fa-home",
        "units.LotAward": "fas fa-home",
        "cases": "fas fa-briefcase",
        "cases.Case": "fas fa-gavel",
        "accounts": "fas fa-lock",
        "accounts.User": "fas fa-user-tie",
    },

    # Admin panel colors (AdminLTE theme)
    "default_icon_parents": "fas fa-chevron-right",
    "default_icon_children": "fas fa-arrow-right",

    # Search configuration
    "search_model": ["accounts.User", "intake.Applicant"],

    # User menu
    "usermenu_links": [],
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small": False,
    "footer_small": False,
    "body_small": False,
    "brand_small": False,
    "brand_colour": "navbar-navy",
    "accent": "accent-primary",
    "tooltip_class": "tooltip-lg",
    "button_size_class": "btn-md",
}
