"""
Django settings for talisay_housing project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-l#!1!(warwnj*ld=dz=-kd13sfzq1s9m460mt8w^p3l4+0##lg"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Allow all hosts for development/testing


# Application definition

INSTALLED_APPS = [
    # Jazzmin admin (must be before django.contrib.admin)
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    'widget_tweaks',
    # Local apps
    'accounts',
    'intake',
    'applications',
    'documents',
    'units',
    'cases',
    'dashboard',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "talisay_housing.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "talisay_housing.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "talisay_housing_db",
        "USER": "postgres",
        "PASSWORD": "1234",
        "HOST": "localhost",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Manila"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (User uploads)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# Login/Logout URLs
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'accounts:dashboard'
LOGOUT_REDIRECT_URL = 'accounts:dashboard'

# =============================================================================
# SMS Configuration (httpSMS - FREE via Android Phone)
# =============================================================================
# httpSMS uses your Android phone as SMS gateway - completely free!
# Just keep the phone on with httpSMS app running

SMS_ENABLED = True  # Real SMS sending is ENABLED
SMS_SERVICE = 'httpsms'  # 'httpsms', 'twilio', or 'semaphore'

# httpSMS Configuration (ACTIVE - FREE)
HTTPSMS_API_KEY = 'pk_aq3fcHBM5uPwQgI-l7x8qy1VKCMRXulIf05z0LvieKMxPO3DmsdWZ2UCY7lE_eJc'
HTTPSMS_API_URL = 'https://api.httpsms.com'  # httpSMS API endpoint

# Twilio Configuration (Backup - Paid)
TWILIO_ACCOUNT_SID = 'ACe90a6af0a068665ed4479c6d303245e9'
TWILIO_AUTH_TOKEN = '8f98a71c0f227237d59990cfa3c48844'
TWILIO_PHONE_NUMBER = '+17126421042'
TWILIO_MESSAGING_SERVICE_SID = 'MGef6b27fa659a0bb41605875f7eddf476'

# Semaphore Configuration (Backup - Philippine)
SEMAPHORE_API_KEY = 'c3f15974a138c3c7aabef97f481781f5'
SEMAPHORE_SENDER_NAME = 'THA'

# =============================================================================
# Jazzmin Admin Configuration
# =============================================================================
JAZZMIN_SETTINGS = {
    # Title & branding
    "site_title": "THA Admin",
    "site_header": "Talisay City Housing Authority",
    "site_brand": "IHSMS",
    "welcome_sign": "Welcome to Talisay City Housing Authority Admin Panel",
    "login_logo": None,

    # UI customization
    "show_ui_builder": True,  # Allow live UI customization
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [],

    # Icons
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "intake": "fas fa-inbox",
        "intake.Applicant": "fas fa-user-check",
        "intake.Barangay": "fas fa-map-marker",
        "intake.Blacklist": "fas fa-ban",
        "intake.CDRRMOCertification": "fas fa-certificate",
        "intake.HouseholdMember": "fas fa-users",
        "intake.QueueEntry": "fas fa-list-ol",
        "intake.SMSLog": "fas fa-sms",
        "applications": "fas fa-file-alt",
        "applications.Application": "fas fa-file-contract",
        "applications.Requirement": "fas fa-checklist",
        "applications.RequirementSubmission": "fas fa-check-circle",
        "applications.SignatoryRoutingStep": "fas fa-route",
        "documents": "fas fa-folder",
        "documents.Document": "fas fa-file",
        "units": "fas fa-building",
        "units.HousingUnit": "fas fa-home",
        "units.LotAward": "fas fa-home",
        "units.OccupancyReport": "fas fa-chart-bar",
        "cases": "fas fa-briefcase",
        "cases.Case": "fas fa-gavel",
        "accounts": "fas fa-lock",
        "accounts.User": "fas fa-user-tie",
    },

    # Admin panel colors (AdminLTE theme)
    "default_icon_parents": "fas fa-chevron-right",
    "default_icon_children": "fas fa-arrow-right",

    # Search configuration
    "search_model": ["accounts.User", "intake.Applicant"],

    # User menu
    "usermenu_links": [],
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small": False,
    "footer_small": False,
    "body_small": False,
    "brand_small": False,
    "brand_colour": "navbar-navy",
    "accent": "accent-primary",
    "tooltip_class": "tooltip-lg",
    "button_size_class": "btn-md",
}
